{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Following the initialisation of the SDK, the user can chat in his already existing chats or add new chats by selecting contacts. The user can also create groups of which they’ll automatically made the admin of. The SDK supports text messages as well images and other type of file uploads such as PDFs. Each message can have a metadata which can be updated, this can be used to handle special messages such as request of payment. Method to see and update user information such as profile image and name is provided"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gcchat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gcchat"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"GCChat is used as an instant chat messaging framework between two mobile devices. It acts as the interface between the client app and our backend to provide instant messaging in individual chats and group chats. All the messages are end to end encrypted to ensure the privacy of the users."}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"GCChat","title":"GCChat","symbolKind":"module","role":"collection","modules":[{"name":"GCChat"}]},"hierarchy":{"paths":[[]]},"topicSections":[{"title":"Articles","identifiers":["doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/Functionality","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/Integration","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/Usage"],"generated":true},{"title":"Classes","identifiers":["doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat"]},{"title":"Protocols","identifiers":["doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChatProtocol"]},{"title":"Structures","identifiers":["doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/ChatMessage","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/ChatParticipant","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/ChatSession","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/ChatUser"]},{"title":"Enumerations","identifiers":["doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChatError"]}],"references":{"doc://com.gamechange.GCChat/documentation/GCChat":{"role":"collection","title":"GCChat","abstract":[{"type":"text","text":"GCChat is used as an instant chat messaging framework between two mobile devices. It acts as the interface between the client app and our backend to provide instant messaging in individual chats and group chats. All the messages are end to end encrypted to ensure the privacy of the users."}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat","kind":"symbol","type":"topic","url":"\/documentation\/gcchat"},"doc://com.gamechange.GCChat/documentation/GCChat/ChatUser":{"role":"symbol","title":"ChatUser","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatUser"}],"abstract":[{"type":"text","text":"Representation of a Chat user"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/ChatUser","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatUser"}],"url":"\/documentation\/gcchat\/chatuser"},"doc://com.gamechange.GCChat/documentation/GCChat/GCChatVersionString":{"role":"symbol","title":"GCChatVersionString","fragments":[{"kind":"identifier","text":"GCChatVersionString"}],"abstract":[{"type":"text","text":"Project version string for GCChat."}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GCChatVersionString","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchatversionstring"},"doc://com.gamechange.GCChat/documentation/GCChat/GCChatVersionNumber":{"role":"symbol","title":"GCChatVersionNumber","fragments":[{"kind":"identifier","text":"GCChatVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for GCChat."}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GCChatVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchatversionnumber"},"doc://com.gamechange.GCChat/documentation/GCChat/ChatParticipant":{"role":"symbol","title":"ChatParticipant","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatParticipant"}],"abstract":[{"type":"text","text":"Representation of a Chat participant"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/ChatParticipant","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatParticipant"}],"url":"\/documentation\/gcchat\/chatparticipant"},"doc://com.gamechange.GCChat/documentation/GCChat/ChatSession":{"role":"symbol","title":"ChatSession","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatSession"}],"abstract":[{"type":"text","text":"Representation of a Chat session"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/ChatSession","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatSession"}],"url":"\/documentation\/gcchat\/chatsession"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChatError":{"role":"symbol","title":"GcChatError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GcChatError"}],"abstract":[{"type":"text","text":"Error enum to handle all the possible failure scenarios"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChatError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GcChatError"}],"url":"\/documentation\/gcchat\/gcchaterror"},"doc://com.gamechange.GCChat/documentation/GCChat/ChatMessage":{"role":"symbol","title":"ChatMessage","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatMessage"}],"abstract":[{"type":"text","text":"Representation of a Chat message"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/ChatMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatMessage"}],"url":"\/documentation\/gcchat\/chatmessage"},"doc://com.gamechange.GCChat/documentation/GCChat/Functionality":{"role":"article","title":"Functionality","abstract":[{"type":"text","text":"This article lists the existing functionality and the WIP functionality"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/Functionality","kind":"article","type":"topic","url":"\/documentation\/gcchat\/functionality"},"doc://com.gamechange.GCChat/documentation/GCChat/Integration":{"role":"article","title":"Integration steps","abstract":[{"type":"text","text":"This article provides the list of steps that need to be followed to integrate the GCChat framework into an app."}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/Integration","kind":"article","type":"topic","url":"\/documentation\/gcchat\/integration"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat":{"role":"symbol","title":"GcChat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GcChat"}],"abstract":[{"type":"text","text":"GcChat: Defines public class for the framework. Use the shared instance of this class to use methods related to chat SDK"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GcChat"}],"url":"\/documentation\/gcchat\/gcchat"},"doc://com.gamechange.GCChat/documentation/GCChat/Usage":{"role":"article","title":"Usage","abstract":[{"type":"text","text":"This article shows the usage of the SDK with some code snippets for the important methods"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/Usage","kind":"article","type":"topic","url":"\/documentation\/gcchat\/usage"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChatProtocol":{"role":"symbol","title":"GcChatProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GcChatProtocol"}],"abstract":[{"type":"text","text":"Protocol which defines the delegate methods received when there’s a live update"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChatProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GcChatProtocol"}],"url":"\/documentation\/gcchat\/gcchatprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Articles","identifiers":["doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/Functionality","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/Integration","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/Usage"],"generated":true},{"title":"Classes","identifiers":["doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat"]},{"title":"Variables","identifiers":["doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GCChatVersionNumber","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GCChatVersionString"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCChat~1documentation~1GCChat~1GcChat\/title","value":"GcChat"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCChat~1documentation~1GCChat~1GcChat\/fragments","value":[{"kind":"identifier","text":"GcChat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}