{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GcChat"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/gcchat\/gcchat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/gcchat\/gcchat"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.gamechange.GCChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.gamechange.GCChat\/objc(pl)NSObject","doc:\/\/com.gamechange.GCChat\/s7CVarArgP","doc:\/\/com.gamechange.GCChat\/s28CustomDebugStringConvertibleP","doc:\/\/com.gamechange.GCChat\/s23CustomStringConvertibleP","doc:\/\/com.gamechange.GCChat\/SQ","doc:\/\/com.gamechange.GCChat\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"GcChat: Defines public class for the framework. Use the shared instance of this class to use methods related to chat SDK"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GcChat"}],"title":"GcChat","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@GCChat@objc(cs)GcChat","modules":[{"name":"GCChat"}],"navigatorTitle":[{"kind":"identifier","text":"GcChat"}]},"hierarchy":{"paths":[["doc:\/\/com.gamechange.GCChat\/documentation\/GCChat"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/addUserToGroup(sessionId:name:phoneNumber:success:failure:)","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/blockUser(sessionId:success:failure:)","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/checkIfRestoreIsRequired(success:failure:)","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/createGroup(participants:title:groupImageFileId:success:failure:)","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/createNewBackup(password:success:failure:)","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/createNewOneToOneChat(phoneNumber:name:imageFileId:success:failure:)","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/deleteBackup(success:failure:)","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/deleteMessage(messageId:success:failure:)","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/getChatHistory(sessionId:success:failure:)","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/getListOfChats(success:failure:)","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/getURLFromFileId(fileId:)","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/getUserInfo(success:failure:)","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/initialize(delegate:jwtToken:phoneNumber:success:failure:)","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/leaveGroup(sessionId:success:failure:)","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/removeUserFromGroup(sessionId:participantId:success:failure:)","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/reportSession(sessionId:category:remarks:messages:success:failure:)","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/restoreBackup(password:success:failure:)","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/sendMessage(chatMessage:session:success:failure:)","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/subscribe(success:failure:)","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/unblockUser(sessionId:success:failure:)","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/unsubscribe()","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/updateFCMToken(token:success:failure:)","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/updateInviteResponse(participantId:accepted:success:failure:)","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/updateMessageMetaInfo(messageId:metaInfo:success:failure:)","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/updateUserInfo(name:imageId:success:failure:)","doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/uploadFile(fileData:fileName:fileType:paramName:success:failure:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/shared"]}],"references":{"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/getURLFromFileId(fileId:)":{"role":"symbol","title":"getURLFromFileId(fileId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getURLFromFileId"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fileId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/getURLFromFileId(fileId:)","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/geturlfromfileid(fileid:)"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/getListOfChats(success:failure:)":{"role":"symbol","title":"getListOfChats(success:failure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getListOfChats"},{"kind":"text","text":"("},{"kind":"externalParam","text":"success"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sessions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatSession","preciseIdentifier":"s:6GCChat11ChatSessionV"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Method to get list of user chat sessions"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/getListOfChats(success:failure:)","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/getlistofchats(success:failure:)"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/subscribe(success:failure:)":{"role":"symbol","title":"subscribe(success:failure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"subscribe"},{"kind":"text","text":"("},{"kind":"externalParam","text":"success"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Subscribe which configures the socket used for listening to messages received by the user. Should be called after initialisation"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/subscribe(success:failure:)","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/subscribe(success:failure:)"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/shared":{"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GcChat","preciseIdentifier":"c:@M@GCChat@objc(cs)GcChat"}],"abstract":[],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/shared","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/shared"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/checkIfRestoreIsRequired(success:failure:)":{"role":"symbol","title":"checkIfRestoreIsRequired(success:failure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkIfRestoreIsRequired"},{"kind":"text","text":"("},{"kind":"externalParam","text":"success"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Checks if a backup restore is required, this has to be called after initialise and before subscribe"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/checkIfRestoreIsRequired(success:failure:)","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/checkifrestoreisrequired(success:failure:)"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/unsubscribe()":{"role":"symbol","title":"unsubscribe()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unsubscribe"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Unsubscribes which disconnects the socket. Should be called when the user logs out"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/unsubscribe()","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/unsubscribe()"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/restoreBackup(password:success:failure:)":{"role":"symbol","title":"restoreBackup(password:success:failure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"restoreBackup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"password"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"success"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Used to restore backup with a password"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/restoreBackup(password:success:failure:)","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/restorebackup(password:success:failure:)"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/createGroup(participants:title:groupImageFileId:success:failure:)":{"role":"symbol","title":"createGroup(participants:title:groupImageFileId:success:failure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createGroup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"participants"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatUser","preciseIdentifier":"s:6GCChat8ChatUserV"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"groupImageFileId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"success"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Method to create a group chat"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/createGroup(participants:title:groupImageFileId:success:failure:)","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/creategroup(participants:title:groupimagefileid:success:failure:)"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/createNewBackup(password:success:failure:)":{"role":"symbol","title":"createNewBackup(password:success:failure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createNewBackup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"password"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"success"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Creates a backup after taking in a password from the user which would be required when restoring backup"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/createNewBackup(password:success:failure:)","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/createnewbackup(password:success:failure:)"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/updateInviteResponse(participantId:accepted:success:failure:)":{"role":"symbol","title":"updateInviteResponse(participantId:accepted:success:failure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateInviteResponse"},{"kind":"text","text":"("},{"kind":"externalParam","text":"participantId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"accepted"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"success"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Method to update invite as accepted\/rejected"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/updateInviteResponse(participantId:accepted:success:failure:)","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/updateinviteresponse(participantid:accepted:success:failure:)"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat":{"role":"symbol","title":"GcChat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GcChat"}],"abstract":[{"type":"text","text":"GcChat: Defines public class for the framework. Use the shared instance of this class to use methods related to chat SDK"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GcChat"}],"url":"\/documentation\/gcchat\/gcchat"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/reportSession(sessionId:category:remarks:messages:success:failure:)":{"role":"symbol","title":"reportSession(sessionId:category:remarks:messages:success:failure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reportSession"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"category"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"remarks"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"messages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:6GCChat11ChatMessageV"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"success"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Method to report session"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/reportSession(sessionId:category:remarks:messages:success:failure:)","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/reportsession(sessionid:category:remarks:messages:success:failure:)"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/addUserToGroup(sessionId:name:phoneNumber:success:failure:)":{"role":"symbol","title":"addUserToGroup(sessionId:name:phoneNumber:success:failure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addUserToGroup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"phoneNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"success"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"ChatParticipant","preciseIdentifier":"s:6GCChat15ChatParticipantV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Method to leave a group"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/addUserToGroup(sessionId:name:phoneNumber:success:failure:)","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/addusertogroup(sessionid:name:phonenumber:success:failure:)"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/deleteMessage(messageId:success:failure:)":{"role":"symbol","title":"deleteMessage(messageId:success:failure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messageId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"success"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Method to delete message"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/deleteMessage(messageId:success:failure:)","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/deletemessage(messageid:success:failure:)"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/createNewOneToOneChat(phoneNumber:name:imageFileId:success:failure:)":{"role":"symbol","title":"createNewOneToOneChat(phoneNumber:name:imageFileId:success:failure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createNewOneToOneChat"},{"kind":"text","text":"("},{"kind":"externalParam","text":"phoneNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"imageFileId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"success"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Method to create a new one to one chat"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/createNewOneToOneChat(phoneNumber:name:imageFileId:success:failure:)","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/createnewonetoonechat(phonenumber:name:imagefileid:success:failure:)"},"doc://com.gamechange.GCChat/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.gamechange.GCChat\/s7CVarArgP"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/blockUser(sessionId:success:failure:)":{"role":"symbol","title":"blockUser(sessionId:success:failure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"blockUser"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"success"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Method to block user"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/blockUser(sessionId:success:failure:)","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/blockuser(sessionid:success:failure:)"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/sendMessage(chatMessage:session:success:failure:)":{"role":"symbol","title":"sendMessage(chatMessage:session:success:failure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"chatMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:6GCChat11ChatMessageV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"session"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatSession","preciseIdentifier":"s:6GCChat11ChatSessionV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"success"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:6GCChat11ChatMessageV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Method to send a message in a particular session"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/sendMessage(chatMessage:session:success:failure:)","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/sendmessage(chatmessage:session:success:failure:)"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/updateFCMToken(token:success:failure:)":{"role":"symbol","title":"updateFCMToken(token:success:failure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateFCMToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"success"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Method to update FCM token"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/updateFCMToken(token:success:failure:)","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/updatefcmtoken(token:success:failure:)"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/uploadFile(fileData:fileName:fileType:paramName:success:failure:)":{"role":"symbol","title":"uploadFile(fileData:fileName:fileType:paramName:success:failure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"uploadFile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fileData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fileName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fileType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"paramName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"success"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"fileId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Method to upload file as a message, profile pic etc"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/uploadFile(fileData:fileName:fileType:paramName:success:failure:)","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/uploadfile(filedata:filename:filetype:paramname:success:failure:)"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/getUserInfo(success:failure:)":{"role":"symbol","title":"getUserInfo(success:failure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getUserInfo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"success"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"ChatUser","preciseIdentifier":"s:6GCChat8ChatUserV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Method to get user info like the profile picture and the name"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/getUserInfo(success:failure:)","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/getuserinfo(success:failure:)"},"doc://com.gamechange.GCChat/documentation/GCChat":{"role":"collection","title":"GCChat","abstract":[{"type":"text","text":"GCChat is used as an instant chat messaging framework between two mobile devices. It acts as the interface between the client app and our backend to provide instant messaging in individual chats and group chats. All the messages are end to end encrypted to ensure the privacy of the users."}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat","kind":"symbol","type":"topic","url":"\/documentation\/gcchat"},"doc://com.gamechange.GCChat/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.gamechange.GCChat\/SH"},"doc://com.gamechange.GCChat/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.gamechange.GCChat\/objc(pl)NSObject"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/leaveGroup(sessionId:success:failure:)":{"role":"symbol","title":"leaveGroup(sessionId:success:failure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"leaveGroup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"success"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Method to leave a group"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/leaveGroup(sessionId:success:failure:)","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/leavegroup(sessionid:success:failure:)"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/deleteBackup(success:failure:)":{"role":"symbol","title":"deleteBackup(success:failure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteBackup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"success"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Used to delete the backup for logged in user"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/deleteBackup(success:failure:)","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/deletebackup(success:failure:)"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/unblockUser(sessionId:success:failure:)":{"role":"symbol","title":"unblockUser(sessionId:success:failure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unblockUser"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"success"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Method to unblock user"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/unblockUser(sessionId:success:failure:)","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/unblockuser(sessionid:success:failure:)"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/updateMessageMetaInfo(messageId:metaInfo:success:failure:)":{"role":"symbol","title":"updateMessageMetaInfo(messageId:metaInfo:success:failure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateMessageMetaInfo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messageId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"metaInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"success"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Method to update metadata of a message"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/updateMessageMetaInfo(messageId:metaInfo:success:failure:)","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/updatemessagemetainfo(messageid:metainfo:success:failure:)"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/initialize(delegate:jwtToken:phoneNumber:success:failure:)":{"role":"symbol","title":"initialize(delegate:jwtToken:phoneNumber:success:failure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GcChatProtocol","preciseIdentifier":"s:6GCChat14GcChatProtocolP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"jwtToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"phoneNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"success"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/initialize(delegate:jwtToken:phoneNumber:success:failure:)","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/initialize(delegate:jwttoken:phonenumber:success:failure:)"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/updateUserInfo(name:imageId:success:failure:)":{"role":"symbol","title":"updateUserInfo(name:imageId:success:failure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateUserInfo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"imageId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"success"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Method to update user info like the profile picture and the name"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/updateUserInfo(name:imageId:success:failure:)","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/updateuserinfo(name:imageid:success:failure:)"},"doc://com.gamechange.GCChat/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.gamechange.GCChat\/SQ"},"doc://com.gamechange.GCChat/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.gamechange.GCChat\/s28CustomDebugStringConvertibleP"},"doc://com.gamechange.GCChat/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.gamechange.GCChat\/s23CustomStringConvertibleP"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/removeUserFromGroup(sessionId:participantId:success:failure:)":{"role":"symbol","title":"removeUserFromGroup(sessionId:participantId:success:failure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeUserFromGroup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"participantId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"success"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Method to remove user from a group"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/removeUserFromGroup(sessionId:participantId:success:failure:)","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/removeuserfromgroup(sessionid:participantid:success:failure:)"},"doc://com.gamechange.GCChat/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.gamechange.GCChat\/objc(cs)NSObject"},"doc://com.gamechange.GCChat/documentation/GCChat/GcChat/getChatHistory(sessionId:success:failure:)":{"role":"symbol","title":"getChatHistory(sessionId:success:failure:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getChatHistory"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"success"},{"kind":"text","text":": (("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"sessions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:6GCChat11ChatMessageV"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"), "},{"kind":"externalParam","text":"failure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":"))"}],"abstract":[{"type":"text","text":"Method to get list of chats of a particular session"}],"identifier":"doc:\/\/com.gamechange.GCChat\/documentation\/GCChat\/GcChat\/getChatHistory(sessionId:success:failure:)","kind":"symbol","type":"topic","url":"\/documentation\/gcchat\/gcchat\/getchathistory(sessionid:success:failure:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GcChat"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GcChat"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GcChat"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.gamechange.GCChat\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"GcChat"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCChat~1documentation~1GCChat~1GcChat\/title","value":"GcChat"},{"op":"replace","path":"\/references\/doc:~1~1com.gamechange.GCChat~1documentation~1GCChat~1GcChat\/fragments","value":[{"kind":"identifier","text":"GcChat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}